### ISSUE TITLE
error connecting to neo4j

### ISSUE THREAD

**Issue by stephanebruckert** [johnnadratowski/golang-bolt-movie-example#2]
Hi, first-time go and neo4j user here. I would like to get the example running, but

    NEO4J_URL=bolt://localhost:7687/ PORT=8080 go run server.go

gives:

> 2017/03/26 21:34:18 error connecting to neo4j: An error occurred initializing connection
> 	An error occurred decoding ack failure message response
> 		Couldn't read expected bytes for message length. Read: 0 Expected: 2.
> Internal Error(*errors.errorString):EOF
> 
>  Stack Trace:
> 
> goroutine 5 [running]:
> runtime/debug.Stack(0x12f4dc8, 0x46, 0xc4200555b0)
> 	/usr/local/Cellar/go/1.8/libexec/src/runtime/debug/stack.go:24 +0x79
> github.com/johnnadratowski/golang-neo4j-bolt-driver/errors.Wrap(0x140fb20, 0xc4200100f0, 0x12f4dc8, 0x46, 0xc4200555b0, 0x1, 0x1, 0xc420055578)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/errors/errors.go:38 +0x1ad
> github.com/johnnadratowski/golang-neo4j-bolt-driver/encoding.Decoder.read(0x140fb60, 0xc42012e460, 0xc420158a10, 0x1010c88, 0x70, 0x12ba280)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/encoding/decoder.go:45 +0x47f
> github.com/johnnadratowski/golang-neo4j-bolt-driver/encoding.Decoder.Decode(0x140fb60, 0xc42012e460, 0xc420158a10, 0x145ffff, 0x12a0000, 0x145b8a0, 0x0)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/encoding/decoder.go:93 +0x43
> github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).ackFailure(0xc42012e460, 0xc4201083c0, 0xc420055778, 0x1)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:408 +0x172
> github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).consume(0xc42012e460, 0xc42012e460, 0xc4201585b0, 0xc42015ffff, 0x12b50c0)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:561 +0x1bf
> github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).sendInit(0xc42012e460, 0x0, 0x0, 0x0, 0x0)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:617 +0x3c4
> github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).initialize(0xc42012e460, 0xc42012e460, 0x4)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:291 +0x168
> github.com/johnnadratowski/golang-neo4j-bolt-driver.newBoltConn(0xc42000c02a, 0x16, 0xc420136030, 0x129e400, 0x1, 0xc420136030)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:102 +0x108
> github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltDriver).OpenNeo(0xc420136030, 0xc42000c02a, 0x16, 0x1, 0xc420134a28, 0x0, 0x3)
> 	/Users/stephane/go/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/driver.go:60 +0x3f
> main.searchHandler(0x1414320, 0xc42012e380, 0xc42011c600)
> 	/Users/stephane/Code/golang-bolt-movie-example/server.go:83 +0x132
> net/http.HandlerFunc.ServeHTTP(0x12f67b8, 0x1414320, 0xc42012e380, 0xc42011c600)
> 	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
> net/http.(*ServeMux).ServeHTTP(0xc420018cc0, 0x1414320, 0xc42012e380, 0xc42011c600)
> 	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
> net/http.serverHandler.ServeHTTP(0xc4200902c0, 0x1414320, 0xc42012e380, 0xc42011c600)
> 	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
> net/http.(*conn).serve(0xc4200c66e0, 0x1414820, 0xc420014600)
> 	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
> created by net/http.(*Server).Serve
> 	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce

I believe I've followed all the instructions, I'm on `go version go1.8 darwin/amd64` and Neo4j 3.1.1
Can you help please?

**Comment by stephanebruckert** [comment]
Fixed running

    NEO4J_URL=bolt://neo4j:MYPASSWORD@localhost:7687/ PORT=8080 go run server.go

instead of just

    NEO4J_URL=bolt://localhost:7687/ PORT=8080 go run server.go
